version: "3.7"
 

services:
  app:
    image: docker_image_name
    container_name: container_name 
    command: "/bin/bash" 
    volumes: 
      # longhand
      # - type: bind #allows file changes to show up immedi
      #   source: ./bind_mount #dir on host machine, ./ points to folder where this yml file is,
      #   target: /home/ubuntu/bind_mount  #dir on container

      - /usr/lib/nvidia-410:/usr/local/nvidia/lib 
      - /usr/lib/nvidia-410:/usr/local/nvidia/lib64 
      - /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib64
      - $HOME/.Xauthority:/root/.Xauthority:rw #maps folder from host to container, RUN on host computer -----: xhost +local:docker 
      
      # - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu

      - ./bind_mount:/home/docker/bind_mount #shorthand
 
      - ./bind_mount/.bashrc:/root/.bashrc
      - ./bind_mount/.bashrc:/home/docker/.bashrc
      - ./bind_mount/user-config.jam:/home/docker/user-config.jam
      - ./bind_mount/user-config.jam:/root/user-config.jam
    devices: 
      # - "/dev/input/event*:/dev/input/event*"
      - "/dev/video*:/dev/video*" 
    environment:
      # - DISPLAY=172.31.224.1:0.0 #pass the DISPLAY environment variable 
      - DISPLAY
      - XAUTHORITY=/root/.Xauthority
    network_mode: "host" #all networking interfaces of host are accessible in container
    ipc: host 
    # ports:
    #   - "8080:8080"
    privileged: true
    stdin_open: true
    tty: true 
  
  app2: #http://localhost:6080/vnc.html?host=localhost&port=6080
    image: universalrobots/ursim_e-series
    container_name: container_ursim  
    networks: 
      ur_sim_net:
        ipv4_address: 192.168.56.101
    ports:
      - "3000:3000"
      - "6080:6080"
      - "29999:29999"
      - "30004:30004"
    environment:
      - ROBOT_MODEL=UR5e
    volumes: 
      - ./bind_mount/rtde_control_loop.urp:/ursim/programs/rtde_control_loop.urp
networks:
  ur_sim_net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24 
          gateway: 192.168.56.1
 