// Generated by gencpp from file robotic_deposition/ur5e_control.msg
// DO NOT EDIT!


#ifndef ROBOTIC_DEPOSITION_MESSAGE_UR5E_CONTROL_H
#define ROBOTIC_DEPOSITION_MESSAGE_UR5E_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/String.h>

namespace robotic_deposition
{
template <class ContainerAllocator>
struct ur5e_control_
{
  typedef ur5e_control_<ContainerAllocator> Type;

  ur5e_control_()
    : inputs()
    , command_type()  {
    }
  ur5e_control_(const ContainerAllocator& _alloc)
    : inputs(_alloc)
    , command_type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _inputs_type;
  _inputs_type inputs;

   typedef  ::std_msgs::String_<ContainerAllocator>  _command_type_type;
  _command_type_type command_type;





  typedef boost::shared_ptr< ::robotic_deposition::ur5e_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotic_deposition::ur5e_control_<ContainerAllocator> const> ConstPtr;

}; // struct ur5e_control_

typedef ::robotic_deposition::ur5e_control_<std::allocator<void> > ur5e_control;

typedef boost::shared_ptr< ::robotic_deposition::ur5e_control > ur5e_controlPtr;
typedef boost::shared_ptr< ::robotic_deposition::ur5e_control const> ur5e_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotic_deposition::ur5e_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotic_deposition::ur5e_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotic_deposition::ur5e_control_<ContainerAllocator1> & lhs, const ::robotic_deposition::ur5e_control_<ContainerAllocator2> & rhs)
{
  return lhs.inputs == rhs.inputs &&
    lhs.command_type == rhs.command_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotic_deposition::ur5e_control_<ContainerAllocator1> & lhs, const ::robotic_deposition::ur5e_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotic_deposition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotic_deposition::ur5e_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotic_deposition::ur5e_control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotic_deposition::ur5e_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6af43574263174a907cc0088df6dfae1";
  }

  static const char* value(const ::robotic_deposition::ur5e_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6af43574263174a9ULL;
  static const uint64_t static_value2 = 0x07cc0088df6dfae1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotic_deposition/ur5e_control";
  }

  static const char* value(const ::robotic_deposition::ur5e_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray inputs\n"
"std_msgs/String  command_type\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::robotic_deposition::ur5e_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputs);
      stream.next(m.command_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ur5e_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotic_deposition::ur5e_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotic_deposition::ur5e_control_<ContainerAllocator>& v)
  {
    s << indent << "inputs: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.inputs);
    s << indent << "command_type: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.command_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTIC_DEPOSITION_MESSAGE_UR5E_CONTROL_H
