; generated by PrusaSlicer 2.4.2+win64 on 2022-08-16 at 01:44:38 UTC

; 

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.20mm
; infill extrusion width = 0.20mm
; solid infill extrusion width = 0.30mm
; top infill extrusion width = 0.30mm
; first layer extrusion width = 0.20mm

M107 ; disable fan
M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F7800 ; move to next layer (0)
G1 E-2 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.914 Y147.914 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.2
G1 F1514
G1 X152.086 Y147.914 E2.05449 ; perimeter
G1 X152.086 Y152.086 E2.10897 ; perimeter
G1 X147.914 Y152.086 E2.16346 ; perimeter
G1 X147.914 Y147.974 E2.21717 ; perimeter
G1 X147.757 Y147.757 F7800 ; move to first perimeter point
G1 F1514
G1 X152.243 Y147.757 E2.27576 ; perimeter
G1 X152.243 Y152.243 E2.33435 ; perimeter
G1 X147.757 Y152.243 E2.39294 ; perimeter
G1 X147.757 Y147.817 E2.45074 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F1514
G1 X152.4 Y147.6 E2.51344 ; perimeter
G1 X152.4 Y152.4 E2.57613 ; perimeter
G1 X147.6 Y152.4 E2.63883 ; perimeter
G1 X147.6 Y147.66 E2.70074 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.70074 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.962 Y151.522 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1514
G1 X148.403 Y151.963 E2.00815 ; infill
G1 X149.589 Y151.963 E2.02365 ; infill
G1 X148.037 Y150.411 E2.05232 ; infill
G1 X148.037 Y149.224 E2.06781 ; infill
G1 X150.776 Y151.963 E2.1184 ; infill
G1 X151.963 Y151.963 E2.1339 ; infill
G1 X148.037 Y148.037 E2.20641 ; infill
G1 X149.224 Y148.037 E2.22191 ; infill
G1 X151.963 Y150.776 E2.27249 ; infill
G1 X151.963 Y149.589 E2.28799 ; infill
G1 X150.411 Y148.037 E2.31666 ; infill
G1 X151.597 Y148.037 E2.33216 ; infill
G1 X152.038 Y148.478 E2.34031 ; infill
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.15
G1 Z.35 F7800 ; move to next layer (1)
G1 E.34031 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1318
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.15
G1 Z.5 F7800 ; move to next layer (2)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
M106 S252.45 ; enable fan
;LAYER_CHANGE
;Z:0.65
;HEIGHT:0.15
G1 Z.65 F7800 ; move to next layer (3)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.15
G1 Z.8 F7800 ; move to next layer (4)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:0.95
;HEIGHT:0.15
G1 Z.95 F7800 ; move to next layer (5)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.1
;HEIGHT:0.15
G1 Z1.1 F7800 ; move to next layer (6)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.25
;HEIGHT:0.15
G1 Z1.25 F7800 ; move to next layer (7)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.15
G1 Z1.4 F7800 ; move to next layer (8)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.55
;HEIGHT:0.15
G1 Z1.55 F7800 ; move to next layer (9)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.7
;HEIGHT:0.15
G1 Z1.7 F7800 ; move to next layer (10)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.15
G1 Z1.85 F7800 ; move to next layer (11)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2
;HEIGHT:0.15
G1 Z2 F7800 ; move to next layer (12)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.15
;HEIGHT:0.15
G1 Z2.15 F7800 ; move to next layer (13)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.3
;HEIGHT:0.15
G1 Z2.3 F7800 ; move to next layer (14)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.45
;HEIGHT:0.15
G1 Z2.45 F7800 ; move to next layer (15)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.15
G1 Z2.6 F7800 ; move to next layer (16)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.75
;HEIGHT:0.15
G1 Z2.75 F7800 ; move to next layer (17)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:2.9
;HEIGHT:0.15
G1 Z2.9 F7800 ; move to next layer (18)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.05
;HEIGHT:0.15
G1 Z3.05 F7800 ; move to next layer (19)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.15
G1 Z3.2 F7800 ; move to next layer (20)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.35
;HEIGHT:0.15
G1 Z3.35 F7800 ; move to next layer (21)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.5
;HEIGHT:0.15
G1 Z3.5 F7800 ; move to next layer (22)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.65
;HEIGHT:0.15
G1 Z3.65 F7800 ; move to next layer (23)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.15
G1 Z3.8 F7800 ; move to next layer (24)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:3.95
;HEIGHT:0.15
G1 Z3.95 F7800 ; move to next layer (25)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.1
;HEIGHT:0.15
G1 Z4.1 F7800 ; move to next layer (26)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.25
;HEIGHT:0.15
G1 Z4.25 F7800 ; move to next layer (27)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.15
G1 Z4.4 F7800 ; move to next layer (28)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.55
;HEIGHT:0.15
G1 Z4.55 F7800 ; move to next layer (29)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.7
;HEIGHT:0.15
G1 Z4.7 F7800 ; move to next layer (30)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:4.85
;HEIGHT:0.15
G1 Z4.85 F7800 ; move to next layer (31)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
;LAYER_CHANGE
;Z:5
;HEIGHT:0.15
G1 Z5 F7800 ; move to next layer (32)
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.936 Y147.936 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
G1 F900
G1 X152.064 Y147.936 E2.04321 ; perimeter
G1 X152.064 Y152.064 E2.08642 ; perimeter
G1 X147.936 Y152.064 E2.12962 ; perimeter
G1 X147.936 Y147.996 E2.1722 ; perimeter
G1 X147.768 Y147.768 F7800 ; move to first perimeter point
G1 F900
G1 X152.232 Y147.768 E2.21892 ; perimeter
G1 X152.232 Y152.232 E2.26564 ; perimeter
G1 X147.768 Y152.232 E2.31236 ; perimeter
G1 X147.768 Y147.828 E2.35846 ; perimeter
G1 X147.6 Y147.6 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F900
G1 X152.4 Y147.6 E2.40869 ; perimeter
G1 X152.4 Y152.4 E2.45892 ; perimeter
G1 X147.6 Y152.4 E2.50915 ; perimeter
G1 X147.6 Y147.66 E2.55876 ; perimeter
G1 X147.986 Y147.704 F7800 ; move inwards before travel
G1 E.55876 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.973 Y151.533 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F1317
G1 X148.391 Y151.951 E2.00618 ; infill
G1 X149.578 Y151.951 E2.0186 ; infill
G1 X148.049 Y150.422 E2.04123 ; infill
G1 X148.049 Y149.236 E2.05365 ; infill
G1 X150.764 Y151.951 E2.09383 ; infill
G1 X151.951 Y151.951 E2.10625 ; infill
G1 X148.049 Y148.049 E2.164 ; infill
G1 X149.236 Y148.049 E2.17642 ; infill
G1 X151.951 Y150.764 E2.21661 ; infill
G1 X151.951 Y149.578 E2.22903 ; infill
G1 X150.422 Y148.049 E2.25165 ; infill
G1 X151.609 Y148.049 E2.26407 ; infill
G1 X152.027 Y148.467 E2.27025 ; infill
G1 E.27025 F2400 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 27.57
; filament used [cm3] = 0.07
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 3m 1s
; estimated printing time (silent mode) = 3m 5s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.2
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.2
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Bioprinter
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 20%
; fill_pattern = alignedrectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.2
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 0
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.2
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.15
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 300
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.2
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Bioprinter
; printer_model = 
; printer_notes = 
; printer_settings_id = Bioprinter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.025
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.3
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.3
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
