; generated by PrusaSlicer 2.4.2+win64 on 2022-08-15 at 22:40:42 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107 ; disable fan
M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F7800 ; move to next layer (0)
G1 E-2 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X98.464 Y98.464 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.42
G1 F1063
G1 X101.536 Y98.464 E2.09631 ; perimeter
G1 X101.536 Y101.536 E2.19262 ; perimeter
G1 X98.464 Y101.536 E2.28893 ; perimeter
G1 X98.464 Y98.524 E2.38336 ; perimeter
G1 X98.087 Y98.087 F7800 ; move to first perimeter point
G1 F1063
G1 X101.913 Y98.087 E2.50332 ; perimeter
G1 X101.913 Y101.913 E2.62327 ; perimeter
G1 X98.087 Y101.913 E2.74323 ; perimeter
G1 X98.087 Y98.147 E2.86131 ; perimeter
G1 X97.71 Y97.71 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F1063
G1 X102.29 Y97.71 E3.00491 ; perimeter
G1 X102.29 Y102.29 E3.14851 ; perimeter
G1 X97.71 Y102.29 E3.29211 ; perimeter
G1 X97.71 Y97.77 E3.43384 ; perimeter
G1 X98.096 Y97.814 F7800 ; move inwards before travel
G1 E1.43384 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.595 Y98.577 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.450661
G1 F1063
G1 X101.253 Y99.235 E2.03153 ; infill
G1 X101.253 Y99.812 E2.05108 ; infill
G1 X100.188 Y98.747 E2.10212 ; infill
G1 X99.612 Y98.747 E2.12167 ; infill
G1 X101.253 Y100.388 E2.20037 ; infill
G1 X101.253 Y100.965 E2.21992 ; infill
G1 X99.035 Y98.747 E2.32626 ; infill
G1 X98.747 Y98.747 E2.33603 ; infill
G1 X98.747 Y99.035 E2.34581 ; infill
G1 X100.965 Y101.253 E2.45214 ; infill
G1 X100.388 Y101.253 E2.47169 ; infill
G1 X98.747 Y99.612 E2.55037 ; infill
G1 X98.747 Y100.189 E2.56992 ; infill
G1 X99.811 Y101.253 E2.62096 ; infill
G1 X99.235 Y101.253 E2.64051 ; infill
G1 X98.577 Y100.596 E2.67204 ; infill
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z.4 F7800 ; move to next layer (1)
G1 E.67204 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X98.539 Y98.539 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.45
G1 F777
G1 X101.461 Y98.539 E2.0989 ; perimeter
G1 X101.461 Y101.461 E2.19779 ; perimeter
G1 X98.539 Y101.461 E2.29669 ; perimeter
G1 X98.539 Y98.599 E2.39355 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F777
G1 X101.868 Y98.132 E2.52001 ; perimeter
G1 X101.868 Y101.868 E2.64646 ; perimeter
G1 X98.132 Y101.868 E2.77291 ; perimeter
G1 X98.132 Y98.192 E2.89734 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F777
G1 X102.275 Y97.725 E3.05135 ; perimeter
G1 X102.275 Y102.275 E3.20536 ; perimeter
G1 X97.725 Y102.275 E3.35937 ; perimeter
G1 X97.725 Y97.785 E3.51135 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E1.51135 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470041
G1 F777
G1 X101.156 Y100.657 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13258 ; infill
G1 X101.156 Y99.448 E2.21832 ; infill
G1 X101.156 Y98.844 E2.23977 ; infill
G1 X98.844 Y101.155 E2.35585 ; infill
G1 X98.844 Y100.551 E2.3773 ; infill
G1 X100.551 Y98.844 E2.46303 ; infill
G1 X99.947 Y98.844 E2.48449 ; infill
G1 X98.844 Y99.947 E2.53988 ; infill
G1 X98.844 Y99.343 E2.56134 ; infill
G1 X99.527 Y98.661 E2.5956 ; infill
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
G1 Z.6 F7800 ; move to next layer (2)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F781
G1 X101.461 Y98.539 E2.69449 ; perimeter
G1 X101.461 Y101.461 E2.79339 ; perimeter
G1 X98.539 Y101.461 E2.89228 ; perimeter
G1 X98.539 Y98.599 E2.98915 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F781
G1 X101.868 Y98.132 E3.1156 ; perimeter
G1 X101.868 Y101.868 E3.24206 ; perimeter
G1 X98.132 Y101.868 E3.36851 ; perimeter
G1 X98.132 Y98.192 E3.49293 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F781
G1 X102.275 Y97.725 E3.64694 ; perimeter
G1 X102.275 Y102.275 E3.80096 ; perimeter
G1 X97.725 Y102.275 E3.95497 ; perimeter
G1 X97.725 Y97.785 E4.10695 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10695 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.561 Y98.659 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Top solid infill
;WIDTH:0.427326
G1 F781
G1 X101.181 Y99.278 E2.02799 ; infill
G1 X101.181 Y99.822 E2.04536 ; infill
G1 X100.178 Y98.819 E2.09066 ; infill
G1 X99.635 Y98.819 E2.10804 ; infill
G1 X101.181 Y100.365 E2.17791 ; infill
G1 X101.181 Y100.909 E2.19528 ; infill
G1 X99.091 Y98.819 E2.28973 ; infill
G1 X98.819 Y98.819 E2.29841 ; infill
G1 X98.819 Y99.091 E2.3071 ; infill
G1 X100.909 Y101.181 E2.40154 ; infill
G1 X100.365 Y101.181 E2.41892 ; infill
G1 X98.819 Y99.635 E2.48878 ; infill
G1 X98.819 Y100.179 E2.50616 ; infill
G1 X99.821 Y101.181 E2.55145 ; infill
G1 X99.278 Y101.181 E2.56883 ; infill
G1 X98.659 Y100.562 E2.59681 ; infill
M106 S255 ; enable fan
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
G1 Z.8 F7800 ; move to next layer (3)
G1 E.59681 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X97.793 Y97.793 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
;WIDTH:0.628705
G1 F600
G1 X97.896 Y97.771 E2.00515 ; perimeter
;WIDTH:0.585811
G1 X98 Y97.75 E2.00992 ; perimeter
;WIDTH:0.54292
G1 X102 Y97.75 E2.17623 ; perimeter
;WIDTH:0.585813
G1 X102.104 Y97.771 E2.181 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y97.793 E2.18615 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E2.1913 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E2.19607 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y101.8 E2.35406 ; perimeter
G1 X102.25 Y102 E2.36238 ; perimeter
;WIDTH:0.585812
G1 X102.229 Y102.104 E2.36715 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E2.3723 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E2.37745 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E2.38222 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E2.54853 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E2.5533 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E2.55845 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E2.5636 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E2.56838 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E2.74894 ; perimeter
G1 X97.771 Y97.896 E2.75372 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E2.75594 ; perimeter
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
G1 Z1 F7800 ; move to next layer (4)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628705
G1 F600
G1 X97.896 Y97.771 E2.7611 ; perimeter
;WIDTH:0.585811
G1 X98 Y97.75 E2.76587 ; perimeter
;WIDTH:0.54292
G1 X102 Y97.75 E2.93217 ; perimeter
;WIDTH:0.585813
G1 X102.104 Y97.771 E2.93694 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y97.793 E2.94209 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E2.94725 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E2.95202 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y101.6 E3.10169 ; perimeter
G1 X102.25 Y102 E3.11832 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E3.12309 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y102.207 E3.12824 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E3.1334 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E3.13817 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E3.30447 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E3.30924 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E3.31439 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E3.31955 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E3.32432 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E3.50489 ; perimeter
G1 X97.771 Y97.896 E3.50966 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E3.51189 ; perimeter
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
G1 Z1.2 F7800 ; move to next layer (5)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628705
G1 F600
G1 X97.896 Y97.771 E3.51704 ; perimeter
;WIDTH:0.585811
G1 X98 Y97.75 E3.52181 ; perimeter
;WIDTH:0.54292
G1 X102 Y97.75 E3.68811 ; perimeter
;WIDTH:0.585813
G1 X102.104 Y97.771 E3.69289 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y97.793 E3.69804 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E3.70319 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E3.70796 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y101.4 E3.84932 ; perimeter
G1 X102.25 Y102 E3.87426 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E3.87904 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E3.88419 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E3.88934 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E3.89411 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E4.06041 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E4.06519 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E4.07034 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E4.07549 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E4.08026 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E4.26083 ; perimeter
G1 X97.771 Y97.896 E4.2656 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E4.26783 ; perimeter
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
G1 Z1.4 F7800 ; move to next layer (6)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628705
G1 F600
G1 X97.896 Y97.771 E4.27298 ; perimeter
;WIDTH:0.585811
G1 X98 Y97.75 E4.27776 ; perimeter
;WIDTH:0.54292
G1 X102 Y97.75 E4.44406 ; perimeter
;WIDTH:0.585813
G1 X102.104 Y97.771 E4.44883 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y97.793 E4.45398 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E4.45913 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E4.46391 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y101.2 E4.59695 ; perimeter
G1 X102.25 Y102 E4.63021 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E4.63498 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E4.64013 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E4.64528 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E4.65006 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E4.81636 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E4.82113 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E4.82628 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E4.83143 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E4.83621 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E5.01677 ; perimeter
G1 X97.771 Y97.896 E5.02155 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E5.02378 ; perimeter
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
G1 Z1.6 F7800 ; move to next layer (7)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E5.02893 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E5.0337 ; perimeter
;WIDTH:0.542921
G1 X101 Y97.75 E5.15843 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E5.2 ; perimeter
;WIDTH:0.585813
G1 X102.104 Y97.771 E5.20478 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y97.793 E5.20993 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E5.21508 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E5.21985 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y101 E5.34458 ; perimeter
G1 X102.25 Y102 E5.38615 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E5.39093 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E5.39608 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E5.40123 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E5.406 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E5.5723 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E5.57708 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E5.58223 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E5.58738 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E5.59215 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E5.77272 ; perimeter
G1 X97.771 Y97.896 E5.77749 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E5.77972 ; perimeter
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
G1 Z1.8 F7800 ; move to next layer (8)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E5.78487 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E5.78965 ; perimeter
;WIDTH:0.542921
G1 X100.8 Y97.75 E5.90606 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E5.95595 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E5.96072 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E5.96587 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E5.97102 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E5.9758 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y100.8 E6.09221 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E6.1421 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E6.14687 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E6.15202 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E6.15717 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E6.16195 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E6.32825 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E6.33302 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E6.33817 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E6.34332 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E6.3481 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E6.52866 ; perimeter
G1 X97.771 Y97.896 E6.53344 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E6.53567 ; perimeter
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
G1 Z2 F7800 ; move to next layer (9)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E6.54082 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E6.54559 ; perimeter
;WIDTH:0.542921
G1 X100.6 Y97.75 E6.65369 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E6.71189 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E6.71666 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E6.72182 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E6.72697 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E6.73174 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y100.6 E6.83984 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E6.89804 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E6.90281 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E6.90797 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E6.91312 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E6.91789 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E7.08419 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E7.08897 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E7.09412 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E7.09927 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E7.10404 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E7.28461 ; perimeter
G1 X97.771 Y97.896 E7.28938 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E7.29161 ; perimeter
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
G1 Z2.2 F7800 ; move to next layer (10)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E7.29676 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E7.30153 ; perimeter
;WIDTH:0.542921
G1 X100.4 Y97.75 E7.40131 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E7.46784 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E7.47261 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E7.47776 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E7.48291 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E7.48768 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y100.4 E7.58747 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E7.65399 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E7.65876 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E7.66391 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E7.66906 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E7.67384 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E7.84014 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E7.84491 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E7.85006 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E7.85521 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E7.85999 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y98 E8.04055 ; perimeter
G1 X97.771 Y97.896 E8.04533 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E8.04755 ; perimeter
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
G1 Z2.4 F7800 ; move to next layer (11)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E8.05271 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E8.05748 ; perimeter
;WIDTH:0.54292
G1 X100.2 Y97.75 E8.14894 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E8.22378 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E8.22855 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E8.2337 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E8.23886 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E8.24363 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y100.2 E8.33509 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E8.40993 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E8.4147 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E8.41985 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E8.42501 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E8.42978 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E8.59608 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E8.60085 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E8.606 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E8.61116 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E8.61593 ; perimeter
;WIDTH:0.585812
G1 X97.75 Y98 E8.7965 ; perimeter
G1 X97.771 Y97.896 E8.80127 ; perimeter
;WIDTH:0.628705
G1 X97.781 Y97.852 E8.8035 ; perimeter
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
G1 Z2.6 F7800 ; move to next layer (12)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E8.80865 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E8.81342 ; perimeter
;WIDTH:0.54292
G1 X100 Y97.75 E8.89657 ; perimeter
G1 X102 Y97.75 E8.97972 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E8.9845 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E8.98965 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E8.9948 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E8.99957 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y100 E9.08272 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E9.16587 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E9.17065 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E9.1758 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E9.18095 ; perimeter
;WIDTH:0.585814
G1 X102 Y102.25 E9.18572 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E9.35202 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E9.3568 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E9.36195 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E9.3671 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E9.37187 ; perimeter
;WIDTH:0.585812
G1 X97.75 Y98 E9.55244 ; perimeter
G1 X97.771 Y97.896 E9.55721 ; perimeter
;WIDTH:0.628705
G1 X97.781 Y97.852 E9.55944 ; perimeter
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
G1 Z2.8 F7800 ; move to next layer (13)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E9.56459 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E9.56937 ; perimeter
;WIDTH:0.54292
G1 X99.8 Y97.75 E9.6442 ; perimeter
G1 X102 Y97.75 E9.73567 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E9.74044 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E9.74559 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E9.75074 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E9.75552 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y99.8 E9.83035 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E9.92182 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E9.92659 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E9.93174 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E9.93689 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E9.94167 ; perimeter
;WIDTH:0.585813
G1 X98 Y102.25 E10.12223 ; perimeter
G1 X97.896 Y102.229 E10.12701 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E10.13216 ; perimeter
;WIDTH:0.628705
G1 X97.771 Y102.104 E10.13731 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E10.14208 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E10.30838 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E10.31316 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E10.31539 ; perimeter
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
G1 Z3 F7800 ; move to next layer (14)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E10.32054 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E10.32531 ; perimeter
;WIDTH:0.54292
G1 X99.6 Y97.75 E10.39183 ; perimeter
;WIDTH:0.585814
G1 X102 Y97.75 E10.50017 ; perimeter
G1 X102.104 Y97.771 E10.50495 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E10.5101 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E10.51525 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E10.52002 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y99.6 E10.58654 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E10.68632 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E10.6911 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E10.69625 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E10.7014 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E10.70617 ; perimeter
;WIDTH:0.585813
G1 X98 Y102.25 E10.88674 ; perimeter
G1 X97.896 Y102.229 E10.89151 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E10.89666 ; perimeter
;WIDTH:0.628705
G1 X97.771 Y102.104 E10.90181 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E10.90659 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E11.07289 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E11.07766 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E11.07989 ; perimeter
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
G1 Z3.2 F7800 ; move to next layer (15)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E11.08504 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E11.08982 ; perimeter
;WIDTH:0.54292
G1 X99.4 Y97.75 E11.14802 ; perimeter
;WIDTH:0.585814
G1 X102 Y97.75 E11.26539 ; perimeter
G1 X102.104 Y97.771 E11.27016 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E11.27531 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E11.28046 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E11.28524 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y99.4 E11.34344 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E11.45154 ; perimeter
;WIDTH:0.585812
G1 X102.229 Y102.104 E11.45631 ; perimeter
;WIDTH:0.628705
G1 X102.207 Y102.207 E11.46146 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E11.46662 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E11.47139 ; perimeter
;WIDTH:0.585813
G1 X98 Y102.25 E11.65196 ; perimeter
G1 X97.896 Y102.229 E11.65673 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E11.66188 ; perimeter
;WIDTH:0.628705
G1 X97.771 Y102.104 E11.66703 ; perimeter
;WIDTH:0.585813
G1 X97.75 Y102 E11.67181 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E11.83811 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E11.84288 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E11.84511 ; perimeter
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
G1 Z3.4 F7800 ; move to next layer (16)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E11.85026 ; perimeter
;WIDTH:0.585813
G1 X98 Y97.75 E11.85503 ; perimeter
;WIDTH:0.54292
G1 X99.2 Y97.75 E11.90492 ; perimeter
;WIDTH:0.585814
G1 X102 Y97.75 E12.03132 ; perimeter
G1 X102.104 Y97.771 E12.03609 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E12.04124 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E12.0464 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E12.05117 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y99.2 E12.10106 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E12.21747 ; perimeter
;WIDTH:0.585813
G1 X102.229 Y102.104 E12.22224 ; perimeter
;WIDTH:0.628706
G1 X102.207 Y102.207 E12.22739 ; perimeter
;WIDTH:0.628705
G1 X102.104 Y102.229 E12.23255 ; perimeter
;WIDTH:0.585811
G1 X102 Y102.25 E12.23732 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E12.40362 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E12.40839 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E12.41354 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E12.4187 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E12.42347 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E12.58977 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E12.59454 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E12.59677 ; perimeter
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
G1 Z3.6 F7800 ; move to next layer (17)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E12.60192 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E12.6067 ; perimeter
;WIDTH:0.54292
G1 X99 Y97.75 E12.64827 ; perimeter
G1 X102 Y97.75 E12.773 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E12.77777 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E12.78292 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E12.78807 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E12.79285 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y99 E12.83442 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E12.95915 ; perimeter
;WIDTH:0.585812
G1 X102.229 Y102.104 E12.96392 ; perimeter
;WIDTH:0.628705
G1 X102.207 Y102.207 E12.96907 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E12.97422 ; perimeter
;WIDTH:0.585812
G1 X102 Y102.25 E12.979 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E13.1453 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E13.15007 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E13.15522 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E13.16037 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E13.16515 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E13.33145 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E13.33622 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E13.33845 ; perimeter
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
G1 Z3.8 F7800 ; move to next layer (18)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E13.3436 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E13.34838 ; perimeter
;WIDTH:0.54292
G1 X98.8 Y97.75 E13.38164 ; perimeter
G1 X102 Y97.75 E13.51468 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E13.51945 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E13.5246 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E13.52975 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E13.53453 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y98.8 E13.56779 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E13.70083 ; perimeter
;WIDTH:0.585812
G1 X102.229 Y102.104 E13.7056 ; perimeter
;WIDTH:0.628705
G1 X102.207 Y102.207 E13.71075 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E13.7159 ; perimeter
;WIDTH:0.585812
G1 X102 Y102.25 E13.72068 ; perimeter
;WIDTH:0.54292
G1 X98 Y102.25 E13.88698 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E13.89175 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E13.8969 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E13.90205 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E13.90683 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E14.07313 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E14.0779 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E14.08013 ; perimeter
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
G1 Z4 F7800 ; move to next layer (19)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E14.08528 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E14.09005 ; perimeter
;WIDTH:0.54292
G1 X98.6 Y97.75 E14.115 ; perimeter
G1 X102 Y97.75 E14.25635 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E14.26113 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E14.26628 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E14.27143 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E14.2762 ; perimeter
;WIDTH:0.542922
G1 X102.25 Y98.6 E14.30115 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y102 E14.4425 ; perimeter
;WIDTH:0.585814
G1 X102.229 Y102.104 E14.44728 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y102.207 E14.45243 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E14.45758 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E14.46235 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E14.62865 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E14.63343 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E14.63858 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E14.64373 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E14.6485 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E14.8148 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E14.81958 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E14.82181 ; perimeter
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
G1 Z4.2 F7800 ; move to next layer (20)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E14.82696 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E14.83173 ; perimeter
;WIDTH:0.54292
G1 X98.4 Y97.75 E14.84836 ; perimeter
G1 X102 Y97.75 E14.99803 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E15.00281 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E15.00796 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E15.01311 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E15.01788 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y98.4 E15.03451 ; perimeter
G1 X102.25 Y102 E15.18418 ; perimeter
;WIDTH:0.585814
G1 X102.229 Y102.104 E15.18896 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y102.207 E15.19411 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E15.19926 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E15.20403 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E15.37033 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E15.37511 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E15.38026 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E15.38541 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E15.39018 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E15.55648 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E15.56126 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E15.56348 ; perimeter
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
G1 Z4.4 F7800 ; move to next layer (21)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E15.56864 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E15.57341 ; perimeter
;WIDTH:0.54292
G1 X98.2 Y97.75 E15.58172 ; perimeter
G1 X102 Y97.75 E15.73971 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E15.74448 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E15.74963 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E15.75479 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E15.75956 ; perimeter
;WIDTH:0.54292
G1 X102.25 Y98.2 E15.76787 ; perimeter
G1 X102.25 Y102 E15.92586 ; perimeter
;WIDTH:0.585814
G1 X102.229 Y102.104 E15.93063 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y102.207 E15.93579 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E15.94094 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E15.94571 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E16.11201 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E16.11678 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E16.12194 ; perimeter
;WIDTH:0.628707
G1 X97.771 Y102.104 E16.12709 ; perimeter
;WIDTH:0.585814
G1 X97.75 Y102 E16.13186 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E16.29816 ; perimeter
;WIDTH:0.585813
G1 X97.771 Y97.896 E16.30293 ; perimeter
;WIDTH:0.628706
G1 X97.781 Y97.852 E16.30516 ; perimeter
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
G1 Z4.6 F7800 ; move to next layer (22)
G1 X97.793 Y97.793 ; move to first perimeter point
;WIDTH:0.628707
G1 F600
G1 X97.896 Y97.771 E16.31031 ; perimeter
;WIDTH:0.585814
G1 X98 Y97.75 E16.31509 ; perimeter
;WIDTH:0.542921
G1 X102 Y97.75 E16.48139 ; perimeter
;WIDTH:0.585814
G1 X102.104 Y97.771 E16.48616 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y97.793 E16.49131 ; perimeter
;WIDTH:0.628706
G1 X102.229 Y97.896 E16.49646 ; perimeter
;WIDTH:0.585813
G1 X102.25 Y98 E16.50124 ; perimeter
G1 X102.25 Y98 F7800 ; move to first perimeter point
;WIDTH:0.54292
G1 F600
G1 X102.25 Y102 E16.66754 ; perimeter
;WIDTH:0.585815
G1 X102.229 Y102.104 E16.67231 ; perimeter
;WIDTH:0.628707
G1 X102.207 Y102.207 E16.67746 ; perimeter
;WIDTH:0.628707
G1 X102.104 Y102.229 E16.68261 ; perimeter
;WIDTH:0.585813
G1 X102 Y102.25 E16.68739 ; perimeter
;WIDTH:0.542921
G1 X98 Y102.25 E16.85369 ; perimeter
;WIDTH:0.585813
G1 X97.896 Y102.229 E16.85846 ; perimeter
;WIDTH:0.628706
G1 X97.793 Y102.207 E16.86361 ; perimeter
;WIDTH:0.628705
G1 X97.771 Y102.104 E16.86876 ; perimeter
;WIDTH:0.585812
G1 X97.75 Y102 E16.87354 ; perimeter
;WIDTH:0.54292
G1 X97.75 Y98 E17.03984 ; perimeter
;WIDTH:0.585815
G1 X97.771 Y97.896 E17.04461 ; perimeter
;WIDTH:0.628707
G1 X97.781 Y97.852 E17.04684 ; perimeter
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
G1 Z4.8 F7800 ; move to next layer (23)
G1 X98.539 Y98.539 ; move to first perimeter (bridge) point
;TYPE:Overhang perimeter
;WIDTH:0.4
;HEIGHT:0.4
G1 F900
G1 X101.461 Y98.539 E17.19948 ; perimeter (bridge)
G1 X101.461 Y101.461 E17.35213 ; perimeter (bridge)
G1 X98.539 Y101.461 E17.50477 ; perimeter (bridge)
G1 X98.539 Y98.599 E17.65428 ; perimeter (bridge)
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
;HEIGHT:0.2
G1 F600
G1 X101.868 Y98.132 E17.78073 ; perimeter
G1 X101.868 Y101.868 E17.90719 ; perimeter
G1 X98.132 Y101.868 E18.03364 ; perimeter
G1 X98.132 Y98.192 E18.15806 ; perimeter
G1 X97.793 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F600
G1 X102.275 Y97.725 E18.30978 ; perimeter
G1 X102.275 Y102.275 E18.46379 ; perimeter
G1 X97.725 Y102.275 E18.6178 ; perimeter
G1 X97.733 Y97.725 E18.77181 ; perimeter
G1 X98.179 Y97.829 F7800 ; move inwards before travel
G1 E16.77181 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.337 Y100.362 F7800 ; move to first infill (bridge) point
G1 E2 F2400 ;  ; unretract
;TYPE:Bridge infill
;WIDTH:0.430508
;HEIGHT:0.4
G1 F3600
G1 X100.565 Y101.134 E2.06606 ; infill (bridge)
G1 X99.885 Y101.134 E2.10719 ; infill (bridge)
G1 X101.134 Y99.885 E2.21408 ; infill (bridge)
G1 X101.134 Y99.206 E2.2552 ; infill (bridge)
G1 X99.206 Y101.134 E2.42025 ; infill (bridge)
G1 X98.866 Y101.134 E2.44081 ; infill (bridge)
G1 X98.866 Y100.794 E2.46137 ; infill (bridge)
G1 X100.794 Y98.866 E2.62641 ; infill (bridge)
G1 X100.115 Y98.866 E2.66754 ; infill (bridge)
G1 X98.866 Y100.115 E2.77442 ; infill (bridge)
G1 X98.866 Y99.435 E2.81554 ; infill (bridge)
G1 X99.638 Y98.663 E2.88159 ; infill (bridge)
M106 S252.45 ; enable fan
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
G1 Z5 F7800 ; move to next layer (24)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F783
G1 X101.461 Y98.539 E2.98049 ; perimeter
G1 X101.461 Y101.461 E3.07938 ; perimeter
G1 X98.539 Y101.461 E3.17828 ; perimeter
G1 X98.539 Y98.599 E3.27514 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F783
G1 X101.868 Y98.132 E3.40159 ; perimeter
G1 X101.868 Y101.868 E3.52805 ; perimeter
G1 X98.132 Y101.868 E3.6545 ; perimeter
G1 X98.132 Y98.192 E3.77893 ; perimeter
G1 X97.793 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F783
G1 X102.275 Y97.725 E3.93064 ; perimeter
G1 X102.275 Y102.275 E4.08465 ; perimeter
G1 X97.725 Y102.275 E4.23866 ; perimeter
G1 X97.733 Y97.725 E4.39268 ; perimeter
G1 X98.179 Y97.829 F7800 ; move inwards before travel
G1 E2.39268 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.341 Y99.439 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Top solid infill
;WIDTH:0.427326
G1 F783
G1 X100.722 Y98.819 E2.02799 ; infill
G1 X100.178 Y98.819 E2.04536 ; infill
G1 X101.181 Y99.822 E2.09066 ; infill
G1 X101.181 Y100.365 E2.10804 ; infill
G1 X99.635 Y98.819 E2.17791 ; infill
G1 X99.091 Y98.819 E2.19528 ; infill
G1 X101.181 Y100.909 E2.28973 ; infill
G1 X101.181 Y101.181 E2.29841 ; infill
G1 X100.909 Y101.181 E2.3071 ; infill
G1 X98.819 Y99.091 E2.40154 ; infill
G1 X98.819 Y99.635 E2.41892 ; infill
G1 X100.365 Y101.181 E2.48878 ; infill
G1 X99.821 Y101.181 E2.50616 ; infill
G1 X98.819 Y100.179 E2.55145 ; infill
G1 X98.819 Y100.722 E2.56883 ; infill
G1 X99.438 Y101.341 E2.59681 ; infill
G1 E.59681 F2400 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 26.08
; filament used [cm3] = 0.06
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 6s
; estimated printing time (silent mode) = 1m 6s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Bioprinter
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Bioprinter
; printer_model = 
; printer_notes = 
; printer_settings_id = Bioprinter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
