; generated by PrusaSlicer 2.4.2+win64 on 2022-08-15 at 22:39:02 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107 ; disable fan
M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F7800 ; move to next layer (0)
G1 E-2 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X98.464 Y98.464 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.42
G1 F1063
G1 X101.536 Y98.464 E2.09631 ; perimeter
G1 X101.536 Y101.536 E2.19262 ; perimeter
G1 X98.464 Y101.536 E2.28893 ; perimeter
G1 X98.464 Y98.524 E2.38336 ; perimeter
G1 X98.087 Y98.087 F7800 ; move to first perimeter point
G1 F1063
G1 X101.913 Y98.087 E2.50332 ; perimeter
G1 X101.913 Y101.913 E2.62327 ; perimeter
G1 X98.087 Y101.913 E2.74323 ; perimeter
G1 X98.087 Y98.147 E2.86131 ; perimeter
G1 X97.71 Y97.71 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F1063
G1 X102.29 Y97.71 E3.00491 ; perimeter
G1 X102.29 Y102.29 E3.14851 ; perimeter
G1 X97.71 Y102.29 E3.29211 ; perimeter
G1 X97.71 Y97.77 E3.43384 ; perimeter
G1 X98.096 Y97.814 F7800 ; move inwards before travel
G1 E1.43384 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.595 Y98.577 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.450661
G1 F1063
G1 X101.253 Y99.235 E2.03153 ; infill
G1 X101.253 Y99.812 E2.05108 ; infill
G1 X100.188 Y98.747 E2.10212 ; infill
G1 X99.612 Y98.747 E2.12167 ; infill
G1 X101.253 Y100.388 E2.20037 ; infill
G1 X101.253 Y100.965 E2.21992 ; infill
G1 X99.035 Y98.747 E2.32625 ; infill
G1 X98.747 Y98.747 E2.33603 ; infill
G1 X98.747 Y99.035 E2.34581 ; infill
G1 X100.965 Y101.253 E2.45214 ; infill
G1 X100.388 Y101.253 E2.47169 ; infill
G1 X98.747 Y99.612 E2.55037 ; infill
G1 X98.747 Y100.189 E2.56992 ; infill
G1 X99.811 Y101.253 E2.62096 ; infill
G1 X99.235 Y101.253 E2.64051 ; infill
G1 X98.577 Y100.596 E2.67204 ; infill
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z.4 F7800 ; move to next layer (1)
G1 E.67204 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X98.539 Y98.539 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.45
G1 F777
G1 X101.461 Y98.539 E2.0989 ; perimeter
G1 X101.461 Y101.461 E2.19779 ; perimeter
G1 X98.539 Y101.461 E2.29669 ; perimeter
G1 X98.539 Y98.599 E2.39355 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F777
G1 X101.868 Y98.132 E2.52001 ; perimeter
G1 X101.868 Y101.868 E2.64646 ; perimeter
G1 X98.132 Y101.868 E2.77291 ; perimeter
G1 X98.132 Y98.192 E2.89734 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F777
G1 X102.275 Y97.725 E3.05135 ; perimeter
G1 X102.275 Y102.275 E3.20536 ; perimeter
G1 X97.725 Y102.275 E3.35937 ; perimeter
G1 X97.725 Y97.785 E3.51135 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E1.51135 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470038
G1 F777
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21832 ; infill
G1 X101.156 Y98.844 E2.23977 ; infill
G1 X98.844 Y101.155 E2.35584 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46303 ; infill
G1 X99.947 Y98.844 E2.48448 ; infill
G1 X98.844 Y99.947 E2.53988 ; infill
G1 X98.844 Y99.343 E2.56133 ; infill
G1 X99.527 Y98.661 E2.59559 ; infill
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
G1 Z.6 F7800 ; move to next layer (2)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69448 ; perimeter
G1 X101.461 Y101.461 E2.79338 ; perimeter
G1 X98.539 Y101.461 E2.89227 ; perimeter
G1 X98.539 Y98.599 E2.98914 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11559 ; perimeter
G1 X101.868 Y101.868 E3.24205 ; perimeter
G1 X98.132 Y101.868 E3.3685 ; perimeter
G1 X98.132 Y98.192 E3.49292 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80095 ; perimeter
G1 X97.725 Y102.275 E3.95496 ; perimeter
G1 X97.725 Y97.785 E4.10694 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10694 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470038
G1 F759
G1 X100.657 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35584 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46303 ; infill
G1 X98.844 Y100.053 E2.48448 ; infill
G1 X99.947 Y101.156 E2.53988 ; infill
G1 X99.343 Y101.156 E2.56133 ; infill
G1 X98.661 Y100.473 E2.59559 ; infill
M106 S252.45 ; enable fan
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
G1 Z.8 F7800 ; move to next layer (3)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69448 ; perimeter
G1 X101.461 Y101.461 E2.79338 ; perimeter
G1 X98.539 Y101.461 E2.89227 ; perimeter
G1 X98.539 Y98.599 E2.98914 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11559 ; perimeter
G1 X101.868 Y101.868 E3.24205 ; perimeter
G1 X98.132 Y101.868 E3.3685 ; perimeter
G1 X98.132 Y98.192 E3.49292 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80095 ; perimeter
G1 X97.725 Y102.275 E3.95496 ; perimeter
G1 X97.725 Y97.785 E4.10694 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10694 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
G1 Z1 F7800 ; move to next layer (4)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03426 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
G1 Z1.2 F7800 ; move to next layer (5)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
G1 Z1.4 F7800 ; move to next layer (6)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03426 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
G1 Z1.6 F7800 ; move to next layer (7)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
G1 Z1.8 F7800 ; move to next layer (8)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
G1 Z2 F7800 ; move to next layer (9)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
G1 Z2.2 F7800 ; move to next layer (10)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
G1 Z2.4 F7800 ; move to next layer (11)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
G1 Z2.6 F7800 ; move to next layer (12)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
G1 Z2.8 F7800 ; move to next layer (13)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
G1 Z3 F7800 ; move to next layer (14)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
G1 Z3.2 F7800 ; move to next layer (15)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
G1 Z3.4 F7800 ; move to next layer (16)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
G1 Z3.6 F7800 ; move to next layer (17)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
G1 Z3.8 F7800 ; move to next layer (18)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
G1 Z4 F7800 ; move to next layer (19)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
G1 Z4.2 F7800 ; move to next layer (20)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23976 ; infill
G1 X101.155 Y101.156 E2.35583 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46302 ; infill
G1 X98.844 Y100.053 E2.48447 ; infill
G1 X99.947 Y101.156 E2.53987 ; infill
G1 X99.343 Y101.156 E2.56132 ; infill
G1 X98.661 Y100.473 E2.59558 ; infill
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
G1 Z4.4 F7800 ; move to next layer (21)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470035
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35583 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46302 ; infill
G1 X99.947 Y98.844 E2.48447 ; infill
G1 X98.844 Y99.947 E2.53987 ; infill
G1 X98.844 Y99.343 E2.56132 ; infill
G1 X99.527 Y98.661 E2.59558 ; infill
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
G1 Z4.6 F7800 ; move to next layer (22)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F759
G1 X101.461 Y98.539 E2.69447 ; perimeter
G1 X101.461 Y101.461 E2.79337 ; perimeter
G1 X98.539 Y101.461 E2.89226 ; perimeter
G1 X98.539 Y98.599 E2.98913 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F759
G1 X101.868 Y98.132 E3.11558 ; perimeter
G1 X101.868 Y101.868 E3.24204 ; perimeter
G1 X98.132 Y101.868 E3.36849 ; perimeter
G1 X98.132 Y98.192 E3.49291 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F759
G1 X102.275 Y97.725 E3.64692 ; perimeter
G1 X102.275 Y102.275 E3.80094 ; perimeter
G1 X97.725 Y102.275 E3.95495 ; perimeter
G1 X97.725 Y97.785 E4.10693 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10693 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X101.339 Y99.527 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470038
G1 F759
G1 X100.656 Y98.844 E2.03427 ; infill
G1 X100.052 Y98.844 E2.05572 ; infill
G1 X101.156 Y99.948 E2.11112 ; infill
G1 X101.156 Y100.552 E2.13257 ; infill
G1 X99.448 Y98.844 E2.21831 ; infill
G1 X98.844 Y98.844 E2.23977 ; infill
G1 X101.155 Y101.156 E2.35584 ; infill
G1 X100.551 Y101.156 E2.37729 ; infill
G1 X98.844 Y99.449 E2.46303 ; infill
G1 X98.844 Y100.053 E2.48448 ; infill
G1 X99.947 Y101.156 E2.53988 ; infill
G1 X99.343 Y101.156 E2.56133 ; infill
G1 X98.661 Y100.473 E2.59559 ; infill
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
G1 Z4.8 F7800 ; move to next layer (23)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F761
G1 X101.461 Y98.539 E2.69448 ; perimeter
G1 X101.461 Y101.461 E2.79338 ; perimeter
G1 X98.539 Y101.461 E2.89227 ; perimeter
G1 X98.539 Y98.599 E2.98914 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F761
G1 X101.868 Y98.132 E3.11559 ; perimeter
G1 X101.868 Y101.868 E3.24205 ; perimeter
G1 X98.132 Y101.868 E3.3685 ; perimeter
G1 X98.132 Y98.192 E3.49292 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F761
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80095 ; perimeter
G1 X97.725 Y102.275 E3.95496 ; perimeter
G1 X97.725 Y97.785 E4.10694 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10694 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.473 Y101.339 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.470038
G1 F761
G1 X101.156 Y100.656 E2.03427 ; infill
G1 X101.156 Y100.052 E2.05572 ; infill
G1 X100.052 Y101.156 E2.11112 ; infill
G1 X99.448 Y101.156 E2.13257 ; infill
G1 X101.156 Y99.448 E2.21831 ; infill
G1 X101.156 Y98.844 E2.23976 ; infill
G1 X98.844 Y101.155 E2.35584 ; infill
G1 X98.844 Y100.551 E2.37729 ; infill
G1 X100.551 Y98.844 E2.46303 ; infill
G1 X99.947 Y98.844 E2.48448 ; infill
G1 X98.844 Y99.947 E2.53988 ; infill
G1 X98.844 Y99.343 E2.56133 ; infill
G1 X99.527 Y98.661 E2.59559 ; infill
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
G1 Z5 F7800 ; move to next layer (24)
G1 X98.539 Y98.539 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.45
G1 F781
G1 X101.461 Y98.539 E2.69448 ; perimeter
G1 X101.461 Y101.461 E2.79338 ; perimeter
G1 X98.539 Y101.461 E2.89227 ; perimeter
G1 X98.539 Y98.599 E2.98914 ; perimeter
G1 X98.132 Y98.132 F7800 ; move to first perimeter point
G1 F781
G1 X101.868 Y98.132 E3.11559 ; perimeter
G1 X101.868 Y101.868 E3.24205 ; perimeter
G1 X98.132 Y101.868 E3.3685 ; perimeter
G1 X98.132 Y98.192 E3.49292 ; perimeter
G1 X97.725 Y97.725 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F781
G1 X102.275 Y97.725 E3.64693 ; perimeter
G1 X102.275 Y102.275 E3.80095 ; perimeter
G1 X97.725 Y102.275 E3.95496 ; perimeter
G1 X97.725 Y97.785 E4.10694 ; perimeter
G1 X98.111 Y97.829 F7800 ; move inwards before travel
G1 E2.10694 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X100.561 Y98.659 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Top solid infill
;WIDTH:0.427326
G1 F781
G1 X101.181 Y99.278 E2.02799 ; infill
G1 X101.181 Y99.822 E2.04536 ; infill
G1 X100.178 Y98.819 E2.09066 ; infill
G1 X99.635 Y98.819 E2.10804 ; infill
G1 X101.181 Y100.365 E2.17791 ; infill
G1 X101.181 Y100.909 E2.19528 ; infill
G1 X99.091 Y98.819 E2.28973 ; infill
G1 X98.819 Y98.819 E2.29841 ; infill
G1 X98.819 Y99.091 E2.3071 ; infill
G1 X100.909 Y101.181 E2.40154 ; infill
G1 X100.365 Y101.181 E2.41892 ; infill
G1 X98.819 Y99.635 E2.48878 ; infill
G1 X98.819 Y100.179 E2.50616 ; infill
G1 X99.821 Y101.181 E2.55145 ; infill
G1 X99.278 Y101.181 E2.56883 ; infill
G1 X98.659 Y100.562 E2.59681 ; infill
G1 E.59681 F2400 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 52.67
; filament used [cm3] = 0.13
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 2m 15s
; estimated printing time (silent mode) = 2m 16s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Bioprinter
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Bioprinter
; printer_model = 
; printer_notes = 
; printer_settings_id = Bioprinter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
