; generated by PrusaSlicer 2.4.2+win64 on 2022-10-06 at 01:54:12 UTC

; 

; external perimeters extrusion width = 0.50mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.50mm
; first layer extrusion width = 0.50mm

M107 ; disable fan
M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.4
G1 Z.4 F7800 ; move to next layer (0)
G1 E-2 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
;WIDTH:0.5
G1 F1133
G1 X152.25 Y147.75 E2.30994 ; perimeter
G1 X152.25 Y152.25 E2.61987 ; perimeter
G1 X147.75 Y152.25 E2.92981 ; perimeter
G1 X147.75 Y147.813 E3.23541 ; perimeter
G1 E1.23541 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X151.247 Y147.874 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Solid infill
;WIDTH:0.519493
G1 F1133
G1 X151.939 Y148.566 E2.0706 ; infill
G1 X151.939 Y149.18 E2.11482 ; infill
G1 X150.82 Y148.061 E2.22896 ; infill
G1 X150.207 Y148.061 E2.27319 ; infill
G1 X151.939 Y149.793 E2.44987 ; infill
G1 X151.939 Y150.406 E2.4941 ; infill
G1 X149.594 Y148.061 E2.73333 ; infill
G1 X148.98 Y148.061 E2.77755 ; infill
G1 X151.939 Y151.02 E3.07933 ; infill
G1 X151.939 Y151.633 E3.12356 ; infill
G1 X148.367 Y148.061 E3.48788 ; infill
G1 X148.061 Y148.061 E3.50999 ; infill
G1 X148.061 Y148.367 E3.53211 ; infill
G1 X151.633 Y151.939 E3.89642 ; infill
G1 X151.019 Y151.939 E3.94065 ; infill
G1 X148.061 Y148.981 E4.24241 ; infill
G1 X148.061 Y149.594 E4.28664 ; infill
G1 X150.406 Y151.939 E4.52585 ; infill
G1 X149.793 Y151.939 E4.57008 ; infill
G1 X148.061 Y150.207 E4.74675 ; infill
G1 X148.061 Y150.82 E4.79098 ; infill
G1 X149.18 Y151.939 E4.9051 ; infill
G1 X148.566 Y151.939 E4.94933 ; infill
G1 X147.874 Y151.247 E5.01991 ; infill
;LAYER_CHANGE
;Z:0.73
;HEIGHT:0.33
G1 Z.73 F7800 ; move to next layer (1)
G1 E3.01991 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
;WIDTH:0.5
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57206 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:1.06
;HEIGHT:0.33
G1 Z1.06 F7800 ; move to next layer (2)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
M106 S255 ; enable fan
;LAYER_CHANGE
;Z:1.39
;HEIGHT:0.33
G1 Z1.39 F7800 ; move to next layer (3)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57206 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:1.72
;HEIGHT:0.33
G1 Z1.72 F7800 ; move to next layer (4)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
;LAYER_CHANGE
;Z:2.05
;HEIGHT:0.33
G1 Z2.05 F7800 ; move to next layer (5)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57206 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:2.38
;HEIGHT:0.33
G1 Z2.38 F7800 ; move to next layer (6)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
;LAYER_CHANGE
;Z:2.71
;HEIGHT:0.33
G1 Z2.71 F7800 ; move to next layer (7)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57206 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:3.04
;HEIGHT:0.33
G1 Z3.04 F7800 ; move to next layer (8)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
;LAYER_CHANGE
;Z:3.37
;HEIGHT:0.33
G1 Z3.37 F7800 ; move to next layer (9)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57206 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:3.7
;HEIGHT:0.33
G1 Z3.7 F7800 ; move to next layer (10)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
;LAYER_CHANGE
;Z:4.03
;HEIGHT:0.33
G1 Z4.03 F7800 ; move to next layer (11)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57207 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
;LAYER_CHANGE
;Z:4.36
;HEIGHT:0.33
G1 Z4.36 F7800 ; move to next layer (12)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.879 Y151.52 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Internal infill
G1 F600
G1 X148.286 Y151.928 E2.03395 ; infill
G1 X149.5 Y151.928 E2.10542 ; infill
G1 X148.072 Y150.5 E2.22437 ; infill
G1 X148.072 Y149.286 E2.29585 ; infill
G1 X150.714 Y151.928 E2.51588 ; infill
G1 X151.928 Y151.928 E2.58736 ; infill
G1 X148.072 Y148.072 E2.90848 ; infill
G1 X149.286 Y148.072 E2.97996 ; infill
G1 X151.928 Y150.714 E3.19999 ; infill
G1 X151.928 Y149.5 E3.27147 ; infill
G1 X150.5 Y148.072 E3.39042 ; infill
G1 X151.714 Y148.072 E3.4619 ; infill
G1 X152.121 Y148.48 E3.49584 ; infill
;LAYER_CHANGE
;Z:4.69
;HEIGHT:0.33
G1 Z4.69 F7800 ; move to next layer (13)
G1 E1.49584 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F600
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 X148.48 Y147.879 F7800 ; move to first infill point
;TYPE:Internal infill
G1 F600
G1 X148.072 Y148.286 E3.09013 ; infill
G1 X148.072 Y149.5 E3.1616 ; infill
G1 X149.5 Y148.072 E3.28055 ; infill
G1 X150.714 Y148.072 E3.35203 ; infill
G1 X148.072 Y150.714 E3.57207 ; infill
G1 X148.072 Y151.928 E3.64354 ; infill
G1 X151.928 Y148.072 E3.96466 ; infill
G1 X151.928 Y149.286 E4.03614 ; infill
G1 X149.286 Y151.928 E4.25617 ; infill
G1 X150.5 Y151.928 E4.32765 ; infill
G1 X151.928 Y150.5 E4.4466 ; infill
G1 X151.928 Y151.714 E4.51808 ; infill
G1 X151.52 Y152.121 E4.55202 ; infill
M106 S252.45 ; enable fan
;LAYER_CHANGE
;Z:5.02
;HEIGHT:0.33
G1 Z5.02 F7800 ; move to next layer (14)
G1 E2.55202 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X147.75 Y147.75 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
G1 F754
G1 X152.25 Y147.75 E2.26497 ; perimeter
G1 X152.25 Y152.25 E2.52995 ; perimeter
G1 X147.75 Y152.25 E2.79492 ; perimeter
G1 X147.75 Y147.813 E3.05618 ; perimeter
G1 E1.05618 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X151.246 Y147.879 F7800 ; move to first infill point
G1 E2 F2400 ;  ; unretract
;TYPE:Top solid infill
;WIDTH:0.503712
G1 F754
G1 X151.928 Y148.561 E2.05731 ; infill
G1 X151.928 Y149.173 E2.09367 ; infill
G1 X150.827 Y148.072 E2.18618 ; infill
G1 X150.215 Y148.072 E2.22254 ; infill
G1 X151.928 Y149.785 E2.36647 ; infill
G1 X151.928 Y150.398 E2.40283 ; infill
G1 X149.602 Y148.072 E2.59818 ; infill
G1 X148.99 Y148.072 E2.63454 ; infill
G1 X151.928 Y151.01 E2.88132 ; infill
G1 X151.928 Y151.622 E2.91768 ; infill
G1 X148.378 Y148.072 E3.21587 ; infill
G1 X148.072 Y148.072 E3.23404 ; infill
G1 X148.072 Y148.378 E3.25223 ; infill
G1 X151.622 Y151.928 E3.55041 ; infill
G1 X151.01 Y151.928 E3.58677 ; infill
G1 X148.072 Y148.99 E3.83353 ; infill
G1 X148.072 Y149.602 E3.86989 ; infill
G1 X150.398 Y151.928 E4.06523 ; infill
G1 X149.785 Y151.928 E4.10159 ; infill
G1 X148.072 Y150.215 E4.24551 ; infill
G1 X148.072 Y150.827 E4.28187 ; infill
G1 X149.173 Y151.928 E4.37437 ; infill
G1 X148.561 Y151.928 E4.41073 ; infill
G1 X147.879 Y151.246 E4.46803 ; infill
G1 E2.46803 F2400 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 40.96
; filament used [cm3] = 0.10
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 17s
; estimated printing time (silent mode) = 1m 18s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,300x0,300x300,0x300
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 1
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.5
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Bioprinter
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 50%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.4
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 0
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.33
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 300
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.42
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_speed = 60
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Bioprinter
; printer_model = 
; printer_notes = 
; printer_settings_id = Bioprinter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.025
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.5
; top_solid_infill_speed = 15
; top_solid_layers = 1
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
