; generated by PrusaSlicer 2.4.2+win64 on 2022-08-15 at 22:43:02 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107 ; disable fan
M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2 F7800 ; move to next layer (0)
G1 E-2 F2400 ; retract
G92 E0 ; reset extrusion distance
G1 X94.19 Y96.646 F7800 ; move to first perimeter point
G1 E2 F2400 ;  ; unretract
;TYPE:External perimeter
;WIDTH:0.42
G1 F1350
G1 X100 Y93.292 E2.21033 ; perimeter
G1 X105.81 Y96.646 E2.42067 ; perimeter
G1 X105.81 Y103.354 E2.631 ; perimeter
G1 X100 Y106.708 E2.84134 ; perimeter
G1 X94.19 Y103.354 E3.05167 ; perimeter
G1 X94.19 Y96.706 E3.26012 ; perimeter
G1 X93.99 Y96.299 F7800 ; move inwards before travel
G1 X93.282 Y96.121 ; move to first perimeter point
G1 F1350
G1 X100 Y92.242 E3.50335 ; perimeter
G1 X106.718 Y96.121 E3.74659 ; perimeter
G1 X106.718 Y103.879 E3.98982 ; perimeter
G1 X100 Y107.758 E4.23305 ; perimeter
G1 X93.282 Y103.879 E4.47628 ; perimeter
G1 X93.282 Y96.181 E4.71763 ; perimeter
G1 X93.682 Y96.121 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z.4 F7800 ; move to next layer (1)
G1 X94.175 Y96.646 ; move to first perimeter point
;WIDTH:0.45
G1 F900
G1 X100 Y93.274 E4.94543 ; perimeter
G1 X105.825 Y96.637 E5.17308 ; perimeter
G1 X105.825 Y103.363 E5.40074 ; perimeter
G1 X100 Y106.726 E5.62839 ; perimeter
G1 X94.175 Y103.363 E5.85605 ; perimeter
G1 X94.175 Y96.706 E6.08138 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E6.34337 ; perimeter
G1 X106.703 Y96.13 E6.60537 ; perimeter
G1 X106.703 Y103.87 E6.86737 ; perimeter
G1 X100 Y107.74 E7.12936 ; perimeter
G1 X93.297 Y103.87 E7.39136 ; perimeter
G1 X93.297 Y96.19 E7.65132 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
G1 Z.6 F7800 ; move to next layer (2)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E7.87913 ; perimeter
G1 X105.825 Y96.637 E8.10678 ; perimeter
G1 X105.825 Y103.363 E8.33443 ; perimeter
G1 X100 Y106.726 E8.56209 ; perimeter
G1 X94.175 Y103.363 E8.78974 ; perimeter
G1 X94.175 Y96.706 E9.01507 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E9.27707 ; perimeter
G1 X106.703 Y96.13 E9.53907 ; perimeter
G1 X106.703 Y103.87 E9.80106 ; perimeter
G1 X100 Y107.74 E10.06306 ; perimeter
G1 X93.297 Y103.87 E10.32505 ; perimeter
G1 X93.297 Y96.19 E10.58502 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
M106 S252.45 ; enable fan
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
G1 Z.8 F7800 ; move to next layer (3)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E10.81282 ; perimeter
G1 X105.825 Y96.637 E11.04047 ; perimeter
G1 X105.825 Y103.363 E11.26813 ; perimeter
G1 X100 Y106.726 E11.49578 ; perimeter
G1 X94.175 Y103.363 E11.72344 ; perimeter
G1 X94.175 Y96.706 E11.94877 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E12.21076 ; perimeter
G1 X106.703 Y96.13 E12.47276 ; perimeter
G1 X106.703 Y103.87 E12.73476 ; perimeter
G1 X100 Y107.74 E12.99675 ; perimeter
G1 X93.297 Y103.87 E13.25875 ; perimeter
G1 X93.297 Y96.19 E13.51871 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
G1 Z1 F7800 ; move to next layer (4)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E13.74652 ; perimeter
G1 X105.825 Y96.637 E13.97417 ; perimeter
G1 X105.825 Y103.363 E14.20182 ; perimeter
G1 X100 Y106.726 E14.42948 ; perimeter
G1 X94.175 Y103.363 E14.65713 ; perimeter
G1 X94.175 Y96.706 E14.88246 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E15.14446 ; perimeter
G1 X106.703 Y96.13 E15.40646 ; perimeter
G1 X106.703 Y103.87 E15.66845 ; perimeter
G1 X100 Y107.74 E15.93045 ; perimeter
G1 X93.297 Y103.87 E16.19244 ; perimeter
G1 X93.297 Y96.19 E16.45241 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
G1 Z1.2 F7800 ; move to next layer (5)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E16.68021 ; perimeter
G1 X105.825 Y96.637 E16.90786 ; perimeter
G1 X105.825 Y103.363 E17.13552 ; perimeter
G1 X100 Y106.726 E17.36317 ; perimeter
G1 X94.175 Y103.363 E17.59083 ; perimeter
G1 X94.175 Y96.706 E17.81616 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E18.07815 ; perimeter
G1 X106.703 Y96.13 E18.34015 ; perimeter
G1 X106.703 Y103.87 E18.60215 ; perimeter
G1 X100 Y107.74 E18.86414 ; perimeter
G1 X93.297 Y103.87 E19.12614 ; perimeter
G1 X93.297 Y96.19 E19.3861 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
G1 Z1.4 F7800 ; move to next layer (6)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E19.61391 ; perimeter
G1 X105.825 Y96.637 E19.84156 ; perimeter
G1 X105.825 Y103.363 E20.06921 ; perimeter
G1 X100 Y106.726 E20.29687 ; perimeter
G1 X94.175 Y103.363 E20.52452 ; perimeter
G1 X94.175 Y96.706 E20.74985 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E21.01185 ; perimeter
G1 X106.703 Y96.13 E21.27385 ; perimeter
G1 X106.703 Y103.87 E21.53584 ; perimeter
G1 X100 Y107.74 E21.79784 ; perimeter
G1 X93.297 Y103.87 E22.05983 ; perimeter
G1 X93.297 Y96.19 E22.3198 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
G1 Z1.6 F7800 ; move to next layer (7)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E22.5476 ; perimeter
G1 X105.825 Y96.637 E22.77525 ; perimeter
G1 X105.825 Y103.363 E23.00291 ; perimeter
G1 X100 Y106.726 E23.23056 ; perimeter
G1 X94.175 Y103.363 E23.45822 ; perimeter
G1 X94.175 Y96.706 E23.68355 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E23.94554 ; perimeter
G1 X106.703 Y96.13 E24.20754 ; perimeter
G1 X106.703 Y103.87 E24.46954 ; perimeter
G1 X100 Y107.74 E24.73153 ; perimeter
G1 X93.297 Y103.87 E24.99353 ; perimeter
G1 X93.297 Y96.19 E25.25349 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
G1 Z1.8 F7800 ; move to next layer (8)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E25.4813 ; perimeter
G1 X105.825 Y96.637 E25.70895 ; perimeter
G1 X105.825 Y103.363 E25.9366 ; perimeter
G1 X100 Y106.726 E26.16426 ; perimeter
G1 X94.175 Y103.363 E26.39191 ; perimeter
G1 X94.175 Y96.706 E26.61724 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E26.87924 ; perimeter
G1 X106.703 Y96.13 E27.14124 ; perimeter
G1 X106.703 Y103.87 E27.40323 ; perimeter
G1 X100 Y107.74 E27.66523 ; perimeter
G1 X93.297 Y103.87 E27.92722 ; perimeter
G1 X93.297 Y96.19 E28.18719 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
G1 Z2 F7800 ; move to next layer (9)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E28.41499 ; perimeter
G1 X105.825 Y96.637 E28.64264 ; perimeter
G1 X105.825 Y103.363 E28.8703 ; perimeter
G1 X100 Y106.726 E29.09795 ; perimeter
G1 X94.175 Y103.363 E29.32561 ; perimeter
G1 X94.175 Y96.706 E29.55094 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E29.81293 ; perimeter
G1 X106.703 Y96.13 E30.07493 ; perimeter
G1 X106.703 Y103.87 E30.33693 ; perimeter
G1 X100 Y107.74 E30.59892 ; perimeter
G1 X93.297 Y103.87 E30.86092 ; perimeter
G1 X93.297 Y96.19 E31.12088 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:2.2
;HEIGHT:0.2
G1 Z2.2 F7800 ; move to next layer (10)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E31.34869 ; perimeter
G1 X105.825 Y96.637 E31.57634 ; perimeter
G1 X105.825 Y103.363 E31.80399 ; perimeter
G1 X100 Y106.726 E32.03165 ; perimeter
G1 X94.175 Y103.363 E32.2593 ; perimeter
G1 X94.175 Y96.706 E32.48463 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E32.74663 ; perimeter
G1 X106.703 Y96.13 E33.00863 ; perimeter
G1 X106.703 Y103.87 E33.27062 ; perimeter
G1 X100 Y107.74 E33.53262 ; perimeter
G1 X93.297 Y103.87 E33.79461 ; perimeter
G1 X93.297 Y96.19 E34.05458 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.2
G1 Z2.4 F7800 ; move to next layer (11)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E34.28238 ; perimeter
G1 X105.825 Y96.637 E34.51003 ; perimeter
G1 X105.825 Y103.363 E34.73769 ; perimeter
G1 X100 Y106.726 E34.96534 ; perimeter
G1 X94.175 Y103.363 E35.193 ; perimeter
G1 X94.175 Y96.706 E35.41833 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E35.68032 ; perimeter
G1 X106.703 Y96.13 E35.94232 ; perimeter
G1 X106.703 Y103.87 E36.20432 ; perimeter
G1 X100 Y107.74 E36.46631 ; perimeter
G1 X93.297 Y103.87 E36.72831 ; perimeter
G1 X93.297 Y96.19 E36.98827 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.2
G1 Z2.6 F7800 ; move to next layer (12)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E37.21608 ; perimeter
G1 X105.825 Y96.637 E37.44373 ; perimeter
G1 X105.825 Y103.363 E37.67138 ; perimeter
G1 X100 Y106.726 E37.89904 ; perimeter
G1 X94.175 Y103.363 E38.12669 ; perimeter
G1 X94.175 Y96.706 E38.35202 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E38.61402 ; perimeter
G1 X106.703 Y96.13 E38.87602 ; perimeter
G1 X106.703 Y103.87 E39.13801 ; perimeter
G1 X100 Y107.74 E39.40001 ; perimeter
G1 X93.297 Y103.87 E39.662 ; perimeter
G1 X93.297 Y96.19 E39.92197 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:2.8
;HEIGHT:0.2
G1 Z2.8 F7800 ; move to next layer (13)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E40.14977 ; perimeter
G1 X105.825 Y96.637 E40.37742 ; perimeter
G1 X105.825 Y103.363 E40.60508 ; perimeter
G1 X100 Y106.726 E40.83273 ; perimeter
G1 X94.175 Y103.363 E41.06039 ; perimeter
G1 X94.175 Y96.706 E41.28572 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E41.54771 ; perimeter
G1 X106.703 Y96.13 E41.80971 ; perimeter
G1 X106.703 Y103.87 E42.07171 ; perimeter
G1 X100 Y107.74 E42.3337 ; perimeter
G1 X93.297 Y103.87 E42.5957 ; perimeter
G1 X93.297 Y96.19 E42.85566 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:3
;HEIGHT:0.2
G1 Z3 F7800 ; move to next layer (14)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E43.08347 ; perimeter
G1 X105.825 Y96.637 E43.31112 ; perimeter
G1 X105.825 Y103.363 E43.53877 ; perimeter
G1 X100 Y106.726 E43.76643 ; perimeter
G1 X94.175 Y103.363 E43.99408 ; perimeter
G1 X94.175 Y96.706 E44.21941 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E44.48141 ; perimeter
G1 X106.703 Y96.13 E44.74341 ; perimeter
G1 X106.703 Y103.87 E45.0054 ; perimeter
G1 X100 Y107.74 E45.2674 ; perimeter
G1 X93.297 Y103.87 E45.52939 ; perimeter
G1 X93.297 Y96.19 E45.78936 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.2
G1 Z3.2 F7800 ; move to next layer (15)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E46.01716 ; perimeter
G1 X105.825 Y96.637 E46.24481 ; perimeter
G1 X105.825 Y103.363 E46.47247 ; perimeter
G1 X100 Y106.726 E46.70012 ; perimeter
G1 X94.175 Y103.363 E46.92778 ; perimeter
G1 X94.175 Y96.706 E47.15311 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E47.4151 ; perimeter
G1 X106.703 Y96.13 E47.6771 ; perimeter
G1 X106.703 Y103.87 E47.9391 ; perimeter
G1 X100 Y107.74 E48.20109 ; perimeter
G1 X93.297 Y103.87 E48.46309 ; perimeter
G1 X93.297 Y96.19 E48.72305 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:3.4
;HEIGHT:0.2
G1 Z3.4 F7800 ; move to next layer (16)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E48.95086 ; perimeter
G1 X105.825 Y96.637 E49.17851 ; perimeter
G1 X105.825 Y103.363 E49.40616 ; perimeter
G1 X100 Y106.726 E49.63382 ; perimeter
G1 X94.175 Y103.363 E49.86147 ; perimeter
G1 X94.175 Y96.706 E50.0868 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E50.3488 ; perimeter
G1 X106.703 Y96.13 E50.6108 ; perimeter
G1 X106.703 Y103.87 E50.87279 ; perimeter
G1 X100 Y107.74 E51.13479 ; perimeter
G1 X93.297 Y103.87 E51.39678 ; perimeter
G1 X93.297 Y96.19 E51.65675 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.2
G1 Z3.6 F7800 ; move to next layer (17)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E51.88455 ; perimeter
G1 X105.825 Y96.637 E52.1122 ; perimeter
G1 X105.825 Y103.363 E52.33986 ; perimeter
G1 X100 Y106.726 E52.56751 ; perimeter
G1 X94.175 Y103.363 E52.79517 ; perimeter
G1 X94.175 Y96.706 E53.0205 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E53.28249 ; perimeter
G1 X106.703 Y96.13 E53.54449 ; perimeter
G1 X106.703 Y103.87 E53.80649 ; perimeter
G1 X100 Y107.74 E54.06848 ; perimeter
G1 X93.297 Y103.87 E54.33048 ; perimeter
G1 X93.297 Y96.19 E54.59044 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.2
G1 Z3.8 F7800 ; move to next layer (18)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E54.81825 ; perimeter
G1 X105.825 Y96.637 E55.0459 ; perimeter
G1 X105.825 Y103.363 E55.27355 ; perimeter
G1 X100 Y106.726 E55.50121 ; perimeter
G1 X94.175 Y103.363 E55.72886 ; perimeter
G1 X94.175 Y96.706 E55.95419 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E56.21619 ; perimeter
G1 X106.703 Y96.13 E56.47819 ; perimeter
G1 X106.703 Y103.87 E56.74018 ; perimeter
G1 X100 Y107.74 E57.00218 ; perimeter
G1 X93.297 Y103.87 E57.26417 ; perimeter
G1 X93.297 Y96.19 E57.52414 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:4
;HEIGHT:0.2
G1 Z4 F7800 ; move to next layer (19)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E57.75194 ; perimeter
G1 X105.825 Y96.637 E57.97959 ; perimeter
G1 X105.825 Y103.363 E58.20725 ; perimeter
G1 X100 Y106.726 E58.4349 ; perimeter
G1 X94.175 Y103.363 E58.66256 ; perimeter
G1 X94.175 Y96.706 E58.88789 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E59.14988 ; perimeter
G1 X106.703 Y96.13 E59.41188 ; perimeter
G1 X106.703 Y103.87 E59.67388 ; perimeter
G1 X100 Y107.74 E59.93587 ; perimeter
G1 X93.297 Y103.87 E60.19787 ; perimeter
G1 X93.297 Y96.19 E60.45783 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:4.2
;HEIGHT:0.2
G1 Z4.2 F7800 ; move to next layer (20)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E60.68564 ; perimeter
G1 X105.825 Y96.637 E60.91329 ; perimeter
G1 X105.825 Y103.363 E61.14094 ; perimeter
G1 X100 Y106.726 E61.3686 ; perimeter
G1 X94.175 Y103.363 E61.59625 ; perimeter
G1 X94.175 Y96.706 E61.82158 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E62.08358 ; perimeter
G1 X106.703 Y96.13 E62.34558 ; perimeter
G1 X106.703 Y103.87 E62.60757 ; perimeter
G1 X100 Y107.74 E62.86957 ; perimeter
G1 X93.297 Y103.87 E63.13156 ; perimeter
G1 X93.297 Y96.19 E63.39153 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:4.4
;HEIGHT:0.2
G1 Z4.4 F7800 ; move to next layer (21)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E63.61933 ; perimeter
G1 X105.825 Y96.637 E63.84698 ; perimeter
G1 X105.825 Y103.363 E64.07464 ; perimeter
G1 X100 Y106.726 E64.30229 ; perimeter
G1 X94.175 Y103.363 E64.52995 ; perimeter
G1 X94.175 Y96.706 E64.75528 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E65.01727 ; perimeter
G1 X106.703 Y96.13 E65.27927 ; perimeter
G1 X106.703 Y103.87 E65.54127 ; perimeter
G1 X100 Y107.74 E65.80326 ; perimeter
G1 X93.297 Y103.87 E66.06526 ; perimeter
G1 X93.297 Y96.19 E66.32522 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:4.6
;HEIGHT:0.2
G1 Z4.6 F7800 ; move to next layer (22)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E66.55303 ; perimeter
G1 X105.825 Y96.637 E66.78068 ; perimeter
G1 X105.825 Y103.363 E67.00833 ; perimeter
G1 X100 Y106.726 E67.23599 ; perimeter
G1 X94.175 Y103.363 E67.46364 ; perimeter
G1 X94.175 Y96.706 E67.68897 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E67.95097 ; perimeter
G1 X106.703 Y96.13 E68.21297 ; perimeter
G1 X106.703 Y103.87 E68.47496 ; perimeter
G1 X100 Y107.74 E68.73696 ; perimeter
G1 X93.297 Y103.87 E68.99895 ; perimeter
G1 X93.297 Y96.19 E69.25892 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.2
G1 Z4.8 F7800 ; move to next layer (23)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E69.48672 ; perimeter
G1 X105.825 Y96.637 E69.71437 ; perimeter
G1 X105.825 Y103.363 E69.94203 ; perimeter
G1 X100 Y106.726 E70.16968 ; perimeter
G1 X94.175 Y103.363 E70.39734 ; perimeter
G1 X94.175 Y96.706 E70.62267 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E70.88466 ; perimeter
G1 X106.703 Y96.13 E71.14666 ; perimeter
G1 X106.703 Y103.87 E71.40866 ; perimeter
G1 X100 Y107.74 E71.67065 ; perimeter
G1 X93.297 Y103.87 E71.93265 ; perimeter
G1 X93.297 Y96.19 E72.19261 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:5
;HEIGHT:0.2
G1 Z5 F7800 ; move to next layer (24)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E72.42042 ; perimeter
G1 X105.825 Y96.637 E72.64807 ; perimeter
G1 X105.825 Y103.363 E72.87572 ; perimeter
G1 X100 Y106.726 E73.10338 ; perimeter
G1 X94.175 Y103.363 E73.33103 ; perimeter
G1 X94.175 Y96.706 E73.55636 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E73.81836 ; perimeter
G1 X106.703 Y96.13 E74.08036 ; perimeter
G1 X106.703 Y103.87 E74.34235 ; perimeter
G1 X100 Y107.74 E74.60435 ; perimeter
G1 X93.297 Y103.87 E74.86634 ; perimeter
G1 X93.297 Y96.19 E75.12631 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:5.2
;HEIGHT:0.2
G1 Z5.2 F7800 ; move to next layer (25)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E75.35411 ; perimeter
G1 X105.825 Y96.637 E75.58176 ; perimeter
G1 X105.825 Y103.363 E75.80942 ; perimeter
G1 X100 Y106.726 E76.03707 ; perimeter
G1 X94.175 Y103.363 E76.26473 ; perimeter
G1 X94.175 Y96.706 E76.49006 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E76.75205 ; perimeter
G1 X106.703 Y96.13 E77.01405 ; perimeter
G1 X106.703 Y103.87 E77.27605 ; perimeter
G1 X100 Y107.74 E77.53804 ; perimeter
G1 X93.297 Y103.87 E77.80004 ; perimeter
G1 X93.297 Y96.19 E78.06 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:5.4
;HEIGHT:0.2
G1 Z5.4 F7800 ; move to next layer (26)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E78.28781 ; perimeter
G1 X105.825 Y96.637 E78.51546 ; perimeter
G1 X105.825 Y103.363 E78.74311 ; perimeter
G1 X100 Y106.726 E78.97077 ; perimeter
G1 X94.175 Y103.363 E79.19842 ; perimeter
G1 X94.175 Y96.706 E79.42375 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E79.68575 ; perimeter
G1 X106.703 Y96.13 E79.94775 ; perimeter
G1 X106.703 Y103.87 E80.20974 ; perimeter
G1 X100 Y107.74 E80.47174 ; perimeter
G1 X93.297 Y103.87 E80.73373 ; perimeter
G1 X93.297 Y96.19 E80.9937 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:5.6
;HEIGHT:0.2
G1 Z5.6 F7800 ; move to next layer (27)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E81.2215 ; perimeter
G1 X105.825 Y96.637 E81.44915 ; perimeter
G1 X105.825 Y103.363 E81.67681 ; perimeter
G1 X100 Y106.726 E81.90446 ; perimeter
G1 X94.175 Y103.363 E82.13212 ; perimeter
G1 X94.175 Y96.706 E82.35745 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E82.61944 ; perimeter
G1 X106.703 Y96.13 E82.88144 ; perimeter
G1 X106.703 Y103.87 E83.14344 ; perimeter
G1 X100 Y107.74 E83.40543 ; perimeter
G1 X93.297 Y103.87 E83.66743 ; perimeter
G1 X93.297 Y96.19 E83.92739 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:5.8
;HEIGHT:0.2
G1 Z5.8 F7800 ; move to next layer (28)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E84.1552 ; perimeter
G1 X105.825 Y96.637 E84.38285 ; perimeter
G1 X105.825 Y103.363 E84.6105 ; perimeter
G1 X100 Y106.726 E84.83816 ; perimeter
G1 X94.175 Y103.363 E85.06581 ; perimeter
G1 X94.175 Y96.706 E85.29114 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E85.55314 ; perimeter
G1 X106.703 Y96.13 E85.81514 ; perimeter
G1 X106.703 Y103.87 E86.07713 ; perimeter
G1 X100 Y107.74 E86.33913 ; perimeter
G1 X93.297 Y103.87 E86.60112 ; perimeter
G1 X93.297 Y96.19 E86.86109 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
;LAYER_CHANGE
;Z:6
;HEIGHT:0.2
G1 Z6 F7800 ; move to next layer (29)
G1 X94.175 Y96.646 ; move to first perimeter point
G1 F900
G1 X100 Y93.274 E87.08889 ; perimeter
G1 X105.825 Y96.637 E87.31654 ; perimeter
G1 X105.825 Y103.363 E87.5442 ; perimeter
G1 X100 Y106.726 E87.77185 ; perimeter
G1 X94.175 Y103.363 E87.99951 ; perimeter
G1 X94.175 Y96.706 E88.22484 ; perimeter
G1 X93.975 Y96.3 F7800 ; move inwards before travel
G1 X93.297 Y96.13 ; move to first perimeter point
G1 F1210
G1 X100 Y92.26 E88.48683 ; perimeter
G1 X106.703 Y96.13 E88.74883 ; perimeter
G1 X106.703 Y103.87 E89.01083 ; perimeter
G1 X100 Y107.74 E89.27282 ; perimeter
G1 X93.297 Y103.87 E89.53482 ; perimeter
G1 X93.297 Y96.19 E89.79478 ; perimeter
G1 X93.697 Y96.13 F7800 ; move inwards before travel
G1 E87.79478 F2400 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 87.79
; filament used [cm3] = 0.21
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 2m 37s
; estimated printing time (silent mode) = 2m 38s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = Bioprinter
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 0
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = Bioprinter
; printer_model = 
; printer_notes = 
; printer_settings_id = Bioprinter
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
